apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: nginx-replica-set
spec:
  replicas: 5
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      name: nginx
      labels:
        app: website
        name: nginx
    spec:
      containers:
        - name: nginx
          image: "nginx:1.11.1-alpine"
          ports:
             - containerPort: 80
